version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: alerto_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: alerto_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: alerto_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./asset/Logo:/app/public/logo

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: ../docker/airflow.webserver.Dockerfile
    container_name: alerto_airflow_web
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DBT_PROFILES_DIR: /opt/dbt
    volumes:
      - airflow_data:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./dbt:/opt/dbt

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: ../docker/airflow.scheduler.Dockerfile
    container_name: alerto_airflow_scheduler
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DBT_PROFILES_DIR: /opt/dbt
    volumes:
      - airflow_data:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./dbt:/opt/dbt

  dbt:
    build:
      context: ./dbt
      dockerfile: ../docker/dbt.Dockerfile
    container_name: alerto_dbt
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./dbt:/dbt
    working_dir: /dbt
    environment:
      DBT_PROFILES_DIR: /dbt

volumes:
  postgres_data:
  airflow_data:
  
